export const listChallenges = [
  {
    id: 1,
    title: 'JavaScript Drum Kit',
    subtitle: 'Challenge No 1',
    featured: ['DOM & INTERFACE', 'CSS DINAMIC', 'AUDIO  + VIDEO'],
    link: 'challenges/1',
  },
  {
    id: 2,
    title: 'CSS + JS Clock',
    subtitle: 'Challenge No 2',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS'],
    link: 'challenges/2',
  },
  {
    id: 3,
    title: 'Playing with CSS Variables and JS',
    subtitle: 'Challenge No 3',
    featured: ['DOM & INTERFACE', 'CSS DINAMIC', 'FUNDAMENTALS'],
    link: 'challenges/3',
  },
  {
    id: 4,
    title: 'Array Cardio Day 1',
    subtitle: 'Challenge No 4',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS'],
    link: 'challenges/4',
  },
  {
    id: 5,
    title: 'Flex Panel Gallery',
    subtitle: 'Challenge No 5',
    featured: ['DOM & INTERFACE', 'CSS DINAMIC', 'FUNDAMENTALS'],
    link: 'challenges/5',
  },
  {
    id: 6,
    title: 'Type Ahead',
    subtitle: 'Challenge No 6',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS'],
    link: 'challenges/6',
  },
  {
    id: 7,
    title: 'Array Cardio Day 2',
    subtitle: 'Challenge No 7',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS'],
    link: 'challenges/7',
  },
  {
    id: 8,
    title: 'Fun with HTML5 Canvas',
    subtitle: 'Challenge No 8',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS'],
    link: 'challenges/8',
  },
  {
    id: 9,
    title: '14 Must Know Dev Tools Tricks',
    subtitle: 'Challenge No 9',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS'],
    link: 'challenges/9',
  },
  {
    id: 10,
    title: 'Hold Shift and Check Checkboxes',
    subtitle: 'Challenge No 10',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS'],
    link: 'challenges/10',
  },
  {
    id: 11,
    title: 'Custom Video Player',
    subtitle: 'Challenge No 11',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS'],
    link: 'challenges/11',
  },
  {
    id: 12,
    title: 'Key Sequence Detection',
    subtitle: 'Challenge No 12',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS'],
    link: 'challenges/12',
  },
  {
    id: 13,
    title: 'Slide in on Scroll',
    subtitle: 'Challenge No 13',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS'],
    link: 'challenges/13',
  },
  {
    id: 14,
    title: 'JavaScript References VS Copying',
    subtitle: 'Challenge No 14',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS'],
    link: 'challenges/14',
  },
  {
    id: 15,
    title: 'LocalStorage and Event Delegation',
    subtitle: 'Challenge No 15',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS'],
    link: 'challenges/15',
  },
  {
    id: 16,
    title: 'Mouse Move Shadow',
    subtitle: 'Challenge No 16',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS'],
    link: 'challenges/16',
  },
  {
    id: 17,
    title: 'Sort Without Articles',
    subtitle: 'Challenge No 17',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS'],
    link: 'challenges/17',
  },
  {
    id: 18,
    title: 'Adding Up Times with Reduce',
    subtitle: 'Challenge No 18',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS'],
    link: 'challenges/18',
  },
  {
    id: 19,
    title: 'Webcam Fun',
    subtitle: 'Challenge No 19',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS', 'EXPERIMENTAL'],
    link: 'challenges/19',
  },
  {
    id: 20,
    title: 'Speech Detection',
    subtitle: 'Challenge No 20',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS','EXPERIMENTAL'],
    link: 'challenges/20',
  },
  {
    id: 21,
    title: 'Geolocation',
    subtitle: 'Challenge No 21',
    featured: ['DOM & INTERFACE', 'HARDWARE ACCESS','EXPERIMENTAL'],
    link: 'challenges/21',
  },
  {
    id: 22,
    title: 'Follow Along Link Highlighter',
    subtitle: 'Challenge No 22',
    featured: ['DOM & INTERFACE', 'CSS DINAMIC'],
    link: 'challenges/22',
  },
  {
    id: 23,
    title: 'Speech Synthesis',
    subtitle: 'Challenge No 23',
    featured: ['DOM & INTERFACE', 'AUDIO + VIDEO','EXPERIMENTAL'],
    link: 'challenges/23',
  },
  {
    id: 24,
    title: 'Sticky Nav',
    subtitle: 'Challenge No 24',
    featured: ['DOM & INTERFACE', 'CSS DINAMIC'],
    link: 'challenges/24',
  },
  {
    id: 25,
    title: 'Event Capture, Propagation, Bubbling and Once',
    subtitle: 'Challenge No 25',
    featured: ['DOM & INTERFACE', 'FUNDAMENTALS'],
    link: 'challenges/25',
  },
  {
    id: 26,
    title: 'Stripe Follow Along Nav',
    subtitle: 'Challenge No 26',
    featured: ['DOM & INTERFACE', 'CSS DINAMIC'],
    link: 'challenges/26',
  },
  {
    id: 27,
    title: 'Click and Drag',
    subtitle: 'Challenge No 27',
    featured: ['DOM & INTERFACE', 'CSS DINAMIC'],
    link: 'challenges/27',
  },
  {
    id: 28,
    title: 'Video Speed Controller',
    subtitle: 'Challenge No 28',
    featured: ['DOM & INTERFACE', 'AUDIO + VIDEO', 'EXPERIMENTAL'],
    link: 'challenges/28',
  },
  {
    id: 29,
    title: 'Countdown Timer',
    subtitle: 'Challenge No 29',
    featured: ['DOM & INTERFACE', 'CSS DINAMIC'],
    link: 'challenges/29',
  },
  {
    id: 30,
    title: 'Whack A Mole',
    subtitle: 'Challenge No 30',
    featured: ['DOM & INTERFACE', 'CSS DINAMIC', 'EXPERIMENTAL'],
    link: 'challenges/30',
  }
];